modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="evolution"
version="1.0.0"
displayName="evolution"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Megaport, MCreator"

[[dependencies.evolution]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




