modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="evolution"
version="1.0.0"
displayName="evolution"
credits="A été fais par JLStrykerz_2_0 discord: JLStrykerz_2_0#9475"
displayURL="https://github.com/strykerzOfficiel/EvolutionMods"
authors="JLStrykerz_2_0"

[[dependencies.evolution]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




